USE [master]
GO

/****** Object:  Database [NACHOPHONE]    Script Date: 07/03/2018 13:26:20 ******/
CREATE DATABASE [NACHOPHONE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NACHOPHONE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\NACHOPHONE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NACHOPHONE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\NACHOPHONE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [NACHOPHONE] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NACHOPHONE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NACHOPHONE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NACHOPHONE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NACHOPHONE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NACHOPHONE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NACHOPHONE] SET ARITHABORT OFF 
GO

ALTER DATABASE [NACHOPHONE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NACHOPHONE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NACHOPHONE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NACHOPHONE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NACHOPHONE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NACHOPHONE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NACHOPHONE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NACHOPHONE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NACHOPHONE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NACHOPHONE] SET  ENABLE_BROKER 
GO

ALTER DATABASE [NACHOPHONE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NACHOPHONE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NACHOPHONE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NACHOPHONE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NACHOPHONE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NACHOPHONE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NACHOPHONE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NACHOPHONE] SET RECOVERY FULL 
GO

ALTER DATABASE [NACHOPHONE] SET  MULTI_USER 
GO

ALTER DATABASE [NACHOPHONE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NACHOPHONE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NACHOPHONE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NACHOPHONE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NACHOPHONE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NACHOPHONE] SET QUERY_STORE = OFF
GO

USE [NACHOPHONE]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [NACHOPHONE] SET  READ_WRITE 
GO

